version: "3.8"
services:
  web:
    build:
      context: .
      target: dev
    env_file: .env
    environment:
      RAILS_DEVELOPMENT_HOSTS: $HOSTNAME
    networks:
      - web
    ports:
      - ${WEB_PORT:-14972}:$PORT
    restart: on-failure
    volumes:
      - ./app:/home/x/r/app
      - ./bin:/home/x/r/bin
      - ./config:/home/x/r/config
      - ./Gemfile.lock:/home/x/r/Gemfile.lock
      - ./Gemfile:/home/x/r/Gemfile
      - ./package.json:/home/x/r/package.json
      - ./spec:/home/x/r/spec
      - ./yarn.lock:/home/x/r/yarn.lock
networks:
  web: {}
