version: '3.7'

services:
  redis:
    image: redis:4.0.9-alpine
    volumes:
      - 'redis_data:/data'
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    restart: always

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
    restart: always

volumes:
  redis_data:
